name: 'WPS daily check in'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  daily_check_in:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt
      - name: 'Working-invite'
        env:
          PUSH_KEY: ${{secrets.PUSH_KEY}}
          USER_ID: ${{secrets.USER_ID}}
        run: python WPS_accept_invitation.py
#       - name: 'Working-signin'
#         env:
#            WPS_SID: ${{secrets.WPS_SID}}
#         run: python WPS_sign_in.py
